### ISSUE TITLE
WP 4.2 - posts can be updated, but no new posts can be created from Gust

### ISSUE THREAD

**Issue by krautsourced** [ideag/gust#60]
Posts need to be created in WP first and saved, then they can be updated in Gust.
New Posts generated in Gust are not being saved in the database
The Save button only shows Update Post now and the dropdown does not work any more.

**Comment by ideag** [comment]
Confirmed, looking for reasons. Seems auto-draft is created and saved in the database, but does not get converted to a "normal" draft for some reason. Work in progress.

**Comment by ideag** [comment]
Just pushed 0.4.1 to wp.org - it should fix auto-draft issue.
