### ISSUE TITLE
WP 4.2.2: /Gust Page now is 404

### ISSUE THREAD

**Issue by lukeed** [ideag/gust#61]
Hey,

After upgrading to latest Wordpress & Gust, my clients can no longer use Gust. Navigating to http://perditionbbq.com/gust gives the 404 page & I'm not sure why

**Comment by ideag** [comment]
@lukeed have you tried flushing permalinks? Visit `WP Admin > Settings > Permalinks` and check if the problem still exists.

**Comment by lukeed** [comment]
Hmm... that did the trick. Still not sure why that happened though...

Thanks!

**Comment by xetryj** [comment]
This solution is not so easy, at it seems to be. I have a detailed manual, maybe it will help someone.
So you go to functions.php and add here:

/\* A function: */
flush_rewrite_rules();

Or 

// And a method of the global object $wp_rewrite
global $wp_rewrite;
$wp_rewrite->flush_rules();

It helped me, hope it will be useful for you.
